# Generated by Django 5.2.16 on 2026-08-02 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('current_city', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('move_date', models.DateField()),
                ('household_size', models.PositiveIntegerField(default=1)),
                ('property_type', models.CharField(choices=[('1RK', '1RK'), ('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('Villa', 'Villa')], default='2BHK', max_length=20)),
                ('assigned_ops', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Planning', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('workflow', models.CharField(choices=[('Planning', 'Planning'), ('Property Search', 'Property Search'), ('Packers & Movers', 'Packers & Movers'), ('Utilities', 'Utilities'), ('Documentation', 'Documentation'), ('Move Day', 'Move Day'), ('Post Move Support', 'Post Move Support'), ('Closure', 'Closure')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('relocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='operations.relocation')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
